---
configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/guilsa/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Dev/GitHub/dotfiles # [@Guil]: updated
dotfiles_repo_version: main   # Replace with your default branch
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible                 # Installed via Pip
  - autoconf
  # - bash-completion           # [@Guil]: May not be needed if `zsh-autocomplete` is installed.
  - doxygen
  - gettext
  - gifsicle
  - git
  - go
  - gpg
  - httpie                    # Friendly cURL
  - iperf
  - libevent
  - sqlite
  - nmap
  - node
  - nvm
  - php
  - pngpaste                  # Save img from clipboard into file (ie. pngpaste thefile.png)
  - ssh-copy-id
  - readline
  - openssl
  - pv                        # Monitor progress of data in cli (a pipe viewer)
  - wget
  - wrk                       # HTTP benchmarking tool
  - zsh-history-substring-search  # Recommended by geerlingguy
  # - zsh-autocomplete
  # - zsh-syntax-highlighting   # Syntax highlighting for the shell zsh
  # - zsh-you-should-use        # Reminds you that you should use one of your existing aliases
  - mosh                      # For mobile / low-bandwidth shell (SSH replacement)
  - bun
  - pnpm
  - vim
  # - colima                  # Container runtimes on MacOS

homebrew_taps:
  - oven-sh/bun

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - photo-sweeper-lite      # Not available in Homebrew
  # - multipass               # VM Ubuntu instances
  # - utm                     # VM Mac OS instances
  # - lulu                    # Note: Ensure latest Mac OS
  # - docker
  # - dropbox
  - bitwarden
  - firefox
  - firefox@developer-edition
  - google-chrome
  - tor-browser
  - github                    # Github Desktop
  - visual-studio-code
  - iterm2
  - licecap                   # record animated GIFs
  - sequel-ace                # SQL GUI
  - keyclu
  - monitorcontrol            # Control display's brightness
  - rectangle                 # Move and resize windows
  - disk-inventory-x
  - protonvpn
  - free-ruler
  - discord
  - signal
  - telegram
  - zoom

# See `geerlingguy.mac.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "Theme - Cobalt2"
  - "TrailingSpaces"
  - "WordingStatus"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
